#    gentoo-prebuilds: Build automation to optimize the size and build-time
#    of gentoo-based container images used for C, C++, and eBPF development
#    Copyright (C) 2024  Michael Przybylski
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
FROM gentoo/stage3:@GENTOO_STAGE3_TAG@

COPY --from=@DOCKER_REPO_PREFIX@/gentoo-mirror-image:@PUSH_TAG@ /var/db/repos/gentoo /var/db/repos/gentoo
COPY --from=@DOCKER_REPO_PREFIX@/gentoo-libbpf-dev-tools:@PUSH_TAG@ /var/cache/binpkgs /var/cache/binpkgs
COPY --from=@DOCKER_REPO_PREFIX@/gentoo-libvirt:@PUSH_TAG@ /var/cache/binpkgs /var/cache/binpkgs
COPY --from=@DOCKER_REPO_PREFIX@/gentoo-custom-toolchain:@PUSH_TAG@ /var/cache/binpkgs /var/cache/binpkgs
COPY --from=@DOCKER_REPO_PREFIX@/gentoo-vcpkg-bootstrap-prereqs:@PUSH_TAG@ /var/cache/binpkgs /var/cache/binpkgs
# This important
# /var/cache/binpkgs/Packages will only list the packages copied in with the last COPY command above without it.
RUN emaint -f binhost
