#    gentoo-prebuilds: Build automation to optimize the size and build-time
#    of gentoo-based container images used for C, C++, and eBPF development
#    Copyright (C) 2024  Michael Przybylski
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
FROM gentoo/stage3:@GENTOO_STAGE3_TAG@ as build-toolchains
ARG GCC_MAJOR_DOT_MINOR_VERSION=14.2
ARG KERNEL_MAJOR_DOT_MINOR_VERSION=4.14
ARG GLIBC_MAJOR_DOT_MINOR_VERSION=2.26

RUN @GENTOO_REPO_MOUNT_ARG@ @EMERGE_FEATURES@ emerge --buildpkg \
    sys-devel/crossdev app-eselect/eselect-repository dev-vcs/git

RUN eselect repository add rescued-ebuilds git https://github.com/mprzybylski/rescued-ebuilds.git && \
    emaint sync -r rescued-ebuilds

RUN eselect repository create crossdev

RUN @GENTOO_REPO_MOUNT_ARG@ @EMERGE_FEATURES@ crossdev --target x86_64-generic-linux-gnu  \
    --gcc "=$GCC_MAJOR_DOT_MINOR_VERSION*" --libc "~$GLIBC_MAJOR_DOT_MINOR_VERSION" -ol rescued-ebuilds  \
    --kernel "~$KERNEL_MAJOR_DOT_MINOR_VERSION" \
    --ex-gdb --portage --verbose --portage --buildpkg

FROM scratch as final
COPY --from=build-toolchains /var/cache/binpkgs /var/cache/binpkgs
