name: Enable dockerd container image store
runs:
  using: "composite"
  steps:
    - name: Modify docker daemon.json and restart docker daemon
      shell: bash
      run: |
        jq '.+{"features":(.features + {"containerd-snapshotter": true})}' </etc/docker/daemon.json | \
            sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker
