name: "Build pre-release container images"
on:
  push:
    branches:
      - main
      - release-*
  pull_request: {}
jobs:
  # build and push gentoo-mirror-image
  build_gentoo_mirror_image:
    name: Build and push gentoo mirror image
    runs-on: ubuntu-22.04
    steps:
      - name: dump docker/daemon.json
        run: cat /etc/docker/daemon.json
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Enable dockerd containerd image store
        uses: ./.github/actions/enable-dockerd-container-image-store
      - name: dump docker/daemon.json after attempted modification
        run: cat /etc/docker/daemon.json
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout, build, and push gentoo-mirror-image
        uses: ./.github/actions/checkout-build-cmake-target
        with:
          target: push-gentoo-mirror-image
          config_args: -DBUILD_NUMBER=${{ github.run_attempt }}
  build_gentoo_custom_toolchain:
    name: Build and push gentoo custom toolchain
    needs: build_gentoo_mirror_image
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Enable dockerd containerd image store
        uses: ./.github/actions/enable-dockerd-container-image-store
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout, build, and push gentoo-mirror-image
        uses: ./.github/actions/checkout-build-cmake-target
        with:
          target: push-gentoo-custom-toolchain
          config_args: -DBUILD_NUMBER=${{ github.run_attempt }}
  build_and_push_gentoo_libbpf_dev_tools:
    name: Build and push gentoo libbpf developer tools
    needs: build_gentoo_mirror_image
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Enable dockerd containerd image store
        uses: ./.github/actions/enable-dockerd-container-image-store
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout, build, and push gentoo-mirror-image
        uses: ./.github/actions/checkout-build-cmake-target
        with:
          target: push-gentoo-libbpf-dev-tools
          config_args: -DBUILD_NUMBER=${{ github.run_attempt }}
  build_and_push_gentoo_libvirt:
    name: Build and push gentoo libvirt and virt-manager
    needs: build_gentoo_mirror_image
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Enable dockerd containerd image store
        uses: ./.github/actions/enable-dockerd-container-image-store
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout, build, and push gentoo-mirror-image
        uses: ./.github/actions/checkout-build-cmake-target
        with:
          target: push-gentoo-libvirt
          config_args: -DBUILD_NUMBER=${{ github.run_attempt }}
  build_and_push_gentoo_vcpkg_bootstrap_prereqs:
    name: Build and push prerequsite packages for vcpkg bootstrap
    needs: build_gentoo_mirror_image
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Enable dockerd containerd image store
        uses: ./.github/actions/enable-dockerd-container-image-store
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout, build, and push gentoo-mirror-image
        uses: ./.github/actions/checkout-build-cmake-target
        with:
          target: push-gentoo-vcpkg-bootstrap-prereqs
          config_args: -DBUILD_NUMBER=${{ github.run_attempt }}
  build_and_push_gentoo_with_binpkgs:
    name: Build and push gentoo-with-binpkgs container image
    needs:
      - build_gentoo_mirror_image
      - build_gentoo_custom_toolchain
      - build_and_push_gentoo_libbpf_dev_tools
      - build_and_push_gentoo_libvirt
      - build_and_push_gentoo_vcpkg_bootstrap_prereqs
    runs-on: ubuntu-22.04
    steps:
      - name: Check out source code
        uses: actions/checkout@v4
      - name: Enable dockerd containerd image store
        uses: ./.github/actions/enable-dockerd-container-image-store
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout, build, and push gentoo-mirror-image
        uses: ./.github/actions/checkout-build-cmake-target
        with:
          target: push-gentoo-with-binpkgs
          config_args: -DBUILD_NUMBER=${{ github.run_attempt }}